# Generated by Django 5.1.4 on 2025-01-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='romm_no',
            new_name='room_no',
        ),
    ]
