# Generated by Django 5.1.5 on 2025-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txref', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
            ],
        ),
    ]
