# Generated by Django 5.1.5 on 2025-01-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_order_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciept',
            old_name='txref',
            new_name='trxref',
        ),
    ]
