# Generated by Django 5.1.5 on 2025-01-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_rename_txref_reciept_trxref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='order_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
