# Generated by Django 5.1.5 on 2025-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_reciept_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
