# Generated by Django 5.1.5 on 2025-01-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_order_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_status',
            new_name='delivered',
        ),
    ]
