# Generated by Django 5.1.5 on 2025-01-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_rename_delivery_status_order_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='order_id',
            field=models.BigIntegerField(),
        ),
    ]
