# Generated by Django 5.1.5 on 2025-01-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_alter_reciept_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='order_id',
        ),
        migrations.AddField(
            model_name='reciept',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bot.order'),
            preserve_default=False,
        ),
    ]
