# Generated by Django 5.1.5 on 2025-01-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_remove_reciept_order_id_reciept_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.order'),
        ),
    ]
